_wandb:
    value:
        cli_version: 0.19.11
        m: []
        python_version: 3.13.3
        t:
            "1":
                - 1
                - 41
                - 55
            "2":
                - 1
                - 41
                - 55
            "3":
                - 2
                - 14
                - 17
                - 23
                - 55
            "4": 3.13.3
            "5": 0.19.11
            "8":
                - 3
                - 5
            "12": 0.19.11
            "13": windows-amd64
batch_size:
    value: 8
img_size:
    value:
        - 256
        - 256
learning_rate:
    value: 0.001
num_epochs:
    value: 1
